version: 1.0.{build}
install:
  - cmd: ECHO "INSTALL OPENCV:"
  - cmd: choco install OpenCV
  - cmd: refreshenv
  - cmd: dir C:\tools\opencv
  - cmd: ECHO %OPENCV_DIR%
  - cmd: ECHO %PATH%
image: Visual Studio 2017
build:
  verbosity: minimal
