version: 1.0.{build}
install:
  - cmd: ECHO "INSTALL OPENCV:"
  - cmd: choco install OpenCV
  - cmd: refreshenv
  - cmd: ECHO %OPENCV-DIR%\bin
  - cmd: ECHO %OPENCV-DIR%\include
  - cmd: ECHO %PATH%
image: Visual Studio 2017
build:
  verbosity: minimal