version: 1.0.{build}
install:
  - cmd: ECHO "INSTALL OPENCV:"
  - cmd: choco install OpenCV
  - cmd: setx OPENCV_DIR C:\tools\opencv\build
  - cmd: refreshenv
image: Visual Studio 2017
build:
  verbosity: minimal